version: '3.8'

services:
  # ============================================================================
  # MongoDB Database
  # ============================================================================
  mongodb:
    image: mongo:6.0
    container_name: assetflow-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: assetflow
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb/data:/data/db
    networks:
      - assetflow-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/assetflow --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ============================================================================
  # Backend (Node.js + Express)
  # ============================================================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: assetflow-backend
    restart: always
    ports:
      - "${BACKEND_PORT:-5000}:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM=${SMTP_FROM}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - BACKUP_ENABLED=${BACKUP_ENABLED}
      - BACKUP_PATH=${BACKUP_PATH}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - assetflow-network
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/.logs:/app/.logs
      - ./backup:/backup
      - ./snapshots:/snapshots
      - ./scripts:/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ============================================================================
  # Frontend (React + Vite)
  # ============================================================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: assetflow-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT:-3000}:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - assetflow-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# ============================================================================
# Networks
# ============================================================================
networks:
  assetflow-network:
    driver: bridge

# ============================================================================
# Volumes
# ============================================================================
volumes:
  mongodb-data:
